export const PROPERTY_DESCRIPTION_UPDATE = "PROPERTY_DESCRIPTION:UPDATE";

export const GET_PROPERTY_INFO = "GET_PROPERTY_INFO";
export const GET_PROPERTY_INFO_SUCCESS = "GET_PROPERTY_INFO:SUCCESS";
export const GET_PROPERTY_INFO_FAILURE = "GET_PROPERTY_INFO:FAILURE";

export const AVAILABILITY_INPUT_UPDATE = "AVAILABILITY_INPUT_UPDATE";
