export const PROPERTY_DESCRIPTION_UPDATE = "PROPERTY_DESCRIPTION:UPDATE";

export const GET_PROPERTY_INFO = "GET_PROPERTY_INFO";
export const GET_PROPERTY_INFO_SUCCESS = "GET_PROPERTY_INFO:SUCCESS";
export const GET_PROPERTY_INFO_FAILURE = "GET_PROPERTY_INFO:FAILURE";

export const GET_ROOMS_INFO = "GET_ROOMS_INFO";
export const GET_ROOMS_INFO_SUCCESS = "GET_ROOMS_INFO:SUCCESS";
export const GET_ROOMS_INFO_FAILURE = "GET_ROOMS_INFO:FAILURE";

export const AVAILABILITY_INPUT_UPDATE = "AVAILABILITY_INPUT_UPDATE";
export const BOOKING_INPUT_UPDATE = "BOOKING_INPUT_UPDATE";

export const BOOK_PROPERTY = "BOOK_PROPERTY";
export const BOOK_PROPERTY_SUCCESS = "BOOK_PROPERTY:SUCCESS";
export const BOOK_PROPERTY_FAILURE = "BOOK_PROPERTY:FAILURE";

export const CHECK_AVAILABILITY = "CHECK_AVAILABILITY";
export const CHECK_AVAILABILITY_SUCCESS = "CHECK_AVAILABILITY:SUCCESS";
export const CHECK_AVAILABILITY_FAILURE = "CHECK_AVAILABILITY:FAILURE";

export const CLEAR_PROPERTY_PAGE = "CLEAR_PROPERTY_PAGE";

export const ROOMS_SELECTED_AMOUNT_UPDATE = "ROOMS_SELECTED_AMOUNT_UPDATE";

export const ROOM_DESCRIPTION_COLLAPSE_TOGGLE = "ROOM_DESCRIPTION_COLLAPSE_TOGGLE";