export const PROPERTY_CALENDAR_UPDATE = "PROPERTY_CALENDAR_UPDATE";

export const AVAILABILITY_ADD = "AVAILABILITY_ADD";
export const AVAILABILITY_ADD_SUCCESS = "AVAILABILITY_ADD_SUCCESS";
export const AVAILABILITY_ADD_FAILURE = "AVAILABILITY_ADD_FAILURE";

export const AVAILABILITY_UPDATE = "AVAILABILITY_UPDATE";
export const AVAILABILITY_UPDATE_SUCCESS = "AVAILABILITY_UPDATE_SUCCESS";
export const AVAILABILITY_UPDATE_FAILURE = "AVAILABILITY_UPDATE_FAILURE";

export const GET_CURRENT_USER_INFO_SUCCESS = "GET_CURRENT_USER_INFO_SUCCESS";
export const GET_CURRENT_USER_INFO_FAILURE = "GET_CURRENT_USER_INFO_FAILURE";
export const GET_CURRENT_USER_INFO = "GET_CURRENT_USER_INFO";
