export const PROPERTY_CALENDAR_UPDATE = "PROPERTY_CALENDAR_UPDATE";
export const PROPERTY_CALENDAR_ADD = "PROPERTY_CALENDAR_ADD";

export const AVAILABILITY_SUBMIT = "AVAILABILITY_SUBMIT";
export const AVAILABILITY_SUBMIT_SUCCESS = "AVAILABILITY_SUBMIT_SUCCESS";
export const AVAILABILITY_SUBMIT_FAILURE = "AVAILABILITY_SUBMIT_FAILURE";

export const SELECTED_ROOM_CHANGE = "SELECTED_ROOM_CHANGE";
