version: "3.1"
services:
    web:
        build: .
        container_name: kudypoditys-frontend
        working_dir: /kudypoditys
        volumes:
            - .:/kudypoditys
        ports:
            - "5000:5000"
