export const USER_SETTINGS_UPDATE = "USER_SETTINGS_UPDATE";

export const USER_SETTINGS_SEND = "USER_SETTINGS_SEND";

export const USER_SETTINGS_SEND_SUCCES = "USER_SETTINGS_SEND_SUCCES";

export const USER_SETTINGS_SEND_FAILURE = "USER_SETTINGS_SEND_FAILURE";

export const UPLOAD_USER_AVATAR = "UPLOAD_USER_AVATAR";

export const UPLOAD_USER_AVATAR_SUCCESS = "UPLOAD_USER_AVATAR_SUCCESS";

export const UPLOAD_USER_AVATAR_FAILURE = "UPLOAD_USER_AVATAR_FAILURE";

export const USER_PASSWORD_CHANGE = "USER_PASSWORD_CHANGE";

export const USER_PASSWORD_CHANGE_SUCCESS = "USER_PASSWORD_CHANGE_SUCCESS";

export const USER_PASSWORD_CHANGE_FAILURE = "USER_PASSWORD_CHANGE_FAILURE";

export const USER_AVATAR_DELETE = "USER_AVATAR_DELETE";
