export const CREATE_REVIEW = "CREATE_REVIEW:SUBMIT";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW:SUCCESS";
export const CREATE_REVIEW_FAILED = "CREATE_REVIEW:FAILED";

export const UPDATE_REVIEW = "UPDATE_REVIEW:UPDATE";
export const UPDATE_RATING = "UPDATE_RATING:UPDATE";