export const GET_MEALS_IN_ROOM = 'GET_MEALS_IN_ROOM';
export const GET_MEAL_IN_ROOM_SUCCESS = 'GET_MEALS_IN_ROOM:SUCCESS';
export const GET_MEAL_IN_ROOM_FAILED = 'GET_MEALS_IN_ROOM:FAILED';
export const CREATE_MEALS_IN_ROOM = 'CREATE_MEALS_IN_ROOM';
export const CREATE_MEALS_IN_ROOM_SUCCESS = 'CREATE_MEALS_IN_ROOM:SUCCESS';
export const CREATE_MEALS_IN_ROOM_FAILED = 'CREATE_MEALS_IN_ROOM:FAILED';
