export const SEND_RESET_PASSWORD_EMAIL = 'SEND_RESET_PASSWORD_EMAIL';
export const SEND_RESET_PASSWORD_EMAIL_SUCCESS = 'SEND_RESET_PASSWORD_EMAIL:SUCSESS';
export const SEND_RESET_PASSWORD_EMAIL_FAILED = 'SEND_RESET_PASSWORD_EMAIL:FAILED';
