export const CREATE_PROPERTY = "CREATE_PROPERTY:SUBMIT";
export const CREATE_PROPERTY_SUCCESS = "CREATE_PROPERTY:SUCCESS";
export const CREATE_PROPERTY_FAILED = "CREATE_PROPERTY:FAILED";

export const UPDATE_PROPERTY = "UPDATE_PROPERTY_TAB:UPDATE";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY:SUCCESS";
export const UPDATE_PROPERTY_FAILED = "UPDATE_PROPERTY:FAILED";