version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      
      - image: circleci/postgres:9.6.5-alpine-ram
	      environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: kudypoditys

    working_directory: ~/bsa-2018-kudypoditys

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test