version: 2
jobs:
    build:
        working_directory: ~/bsa-2018-kudypoditys
        docker:
            - image: docker:17.05.0-ce-git
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Install dependencies
                  command: |
                      apk add --no-cache py-pip=9.0.0-r1 jq
                      pip install awscli==1.11.76
            - run:
                  name: Build application Docker image
                  command: |
                      docker build -t app .
            - deploy:
                  command: |
                      sh ./deploy.sh
general:
    branches:
        only:
            - master # list of branches to build
