export const CURRENCIES_GET = 'CURRENCIES:GET';
export const CURENCY_SELECT = 'CURRENCY:SELECT';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT:SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT:FAILED';