export const CURRENCIES_GET = 'CURRENCIES:GET';
export const CURRENCY_SELECT = 'CURRENCY:SELECT';
export const CURRENCY_RATE_GET = 'CURRENCY_RATE:GET'
export const CURRENCY_RATE_GET_FAILED = 'CURRENCY_RATE_GET:FAILED'

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT:SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT:FAILED';