export const PROPERTY_ITEM_UPDATE = 'PROPERTY_LIST_ITEM:UPDATE';
export const PROPERTY_ITEM_DELETE = 'PROPERTY_LIST_ITEM:DELETE';
export const PROPERTY_ITEM_INSERT = 'PROPERTY_LIST_ITEM:INSERT';
export const FETCH_PROPERTY_ITEM = 'FETCH_PROPERTY_ITEM:FETCH';
export const FETCH_ALL_PROPERTIES = 'FETCH_ALL_PROPERTIES:FETCH';
export const FOUND_PROPERTIES_INSERT_ALL = 'FOUND_PROPERTIES_INSERT_ALL:INSERT';