export const PROPERTY_LIST_ITEM_UPDATE = 'PROPERTY_LIST_ITEM:UPDATE';
export const PROPERTY_LIST_ITEM_DELETE = 'PROPERTY_LIST_ITEM:DELETE';
export const PROPERTY_LIST_ITEM_INSERT = 'PROPERTY_LIST_ITEM:INSERT';