export const PROPERTY_UPDATE = "PROPERTY_UPDATE";
export const PROPERTY_UPDATE_INIT = "PROPERTY_UPDATE_INIT";
export const PROPERTY_UPDATE_SUCCESS = "PROPERTY_UPDATE_SUCCESS";
export const PROPERTY_UPDATE_FAIL = "PROPERTY_UPDATE_FAIL";