export const ROOM_SUMMARY_PRICE_GET = 'ROOM_SUMMARY_PRICE:GET';
export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS:SUCCESS';
export const GET_ROOMS_FAILURE = 'GET_ROOMS:FAILURE';
