export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN:SUCCESS";
export const LOGIN_FAILURE = "LOGIN:FAILURE";

export const LOGOUT = "LOGOUT";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER:SUCCESS";
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER:FAILURE";

export const RESET_LOGIN = 'RESET_LOGIN';