export const SEARCH_UPDATE = 'SEARCH:UPDATE';
export const SEARCH_UPDATE_SUCCESS = 'SEARCH_UPDATE:SUCCESS';
export const SEARCH_UPDATE_FAILED= 'SEARCH_UPDATE:FAILED';
export const SEARCH_SUBMIT_SUCCESS ='SEARCH_SUBMIT:SUCCES';
export const SEARCH_SUBMIT_FAILED = 'SEARCH_SUBMIT:FAILED';
export const SEARCH_SUBMIT = 'SEARCH:SUBMIT';
export const CLEAR_SEARCH_PAGE = 'CLEAR_SEARCH_PAGE';