export const GET_CURRENT_USER_INFO_SUCCESS = "GET_CURRENT_USER_INFO_SUCCESS";
export const GET_CURRENT_USER_INFO_FAILURE = "GET_CURRENT_USER_INFO_FAILURE";
export const GET_CURRENT_USER_INFO = "GET_CURRENT_USER_INFO";
