export const GET_CURRENT_USER_INFO_SUCCESS = "GET_CURRENT_USER_INFO_SUCCESS";
export const GET_CURRENT_USER_INFO_FAILURE = "GET_CURRENT_USER_INFO_FAILURE";
export const GET_CURRENT_USER_INFO = "GET_CURRENT_USER_INFO";
export const CHOOSE_PROPERTY = "GET_CURRENT_USER_INFO";
export const UNCHOOSE_PROPERTY = "GET_CURRENT_USER_INFO";
export const CANCEL_OWNER_BOOKING = "CANCEL_OWNER_BOOKING";
export const CANCEL_OWNER_BOOKING_SUCCESS = "CANCEL_OWNER_BOOKING:SUCCESS";
export const CANCEL_OWNER_BOOKING_FAILURE = "CANCEL_OWNER_BOOKING:FAILURE";
