export const USER_SETTINGS_UPDATE = "USER_SETTINGS_UPDATE";

export const USER_SETTINGS_SEND = "USER_SETTINGS_SEND";

export const USER_SETTINGS_SEND_SUCCES = "USER_SETTINGS_SEND_SUCCES";

export const USER_SETTINGS_SEND_FAILURE = "USER_SETTINGS_SEND_FAILURE";

export const UPLOAD_USER_AVATAR = "UPLOAD_USER_AVATAR";

export const UPLOAD_USER_AVATAR_SUCCESS = "UPLOAD_USER_AVATAR_SUCCESS";

export const UPLOAD_USER_AVATAR_FAILURE = "UPLOAD_USER_AVATAR_FAILURE";

export const USER_PASSWORD_RESET = "USER_PASSWORD_RESET";

export const USER_PASSWORD_RESET_SUCCESS = "USER_PASSWORD_RESET_SUCCESS";

export const USER_PASSWORD_RESET_FAILURE = "USER_PASSWORD_RESET_FAILURE";
