export const USER_SETTINGS_UPDATE = "USER_SETTINGS_UPDATE";

export const USER_SETTINGS_SEND = "USER_SETTINGS_SEND";

export const USER_SETTINGS_SEND_SUCCES = "USER_SETTINGS_SEND_SUCCES";

export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE";
