export const GET_USER_BOOKINGS = "GET_USER_BOOKINGS";
export const GET_USER_BOOKINGS_SUCCESS = "GET_USER_BOOKINGS:SUCCESS";
export const GET_USER_BOOKINGS_FAILURE = "GET_USER_BOOKINGS:FAILURE";

export const CHOOSE_BOOKING = "CHOOSE_BOOKING";

export const UNCHOOSE_BOOKING = "UNCHOOSE_BOOKING";
export const CANCEL_BOOKING = "CANCEL_BOOKING";
export const CANCEL_BOOKING_SUCCESS = "CANCEL_BOOKING:SUCCESS";
export const CANCEL_BOOKING_FAILURE = "CANCEL_BOOKING:FAILURE";
