export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCSESS = 'RESET_PASSWORD:SUCSESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD:FAILED';

export const SAVE_URL_QUERY = 'SAVE_URL_QUERY';
